# Generated by Django 3.2.13 on 2022-05-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('username', models.CharField(default='', max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('dob', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
